viam-orb-slam3:
    image_amd64: ghcr.io/viamrobotics/canon:amd64
    image_arm64: ghcr.io/viamrobotics/canon:arm64
    minimum_date: 2022-12-20T18:49:25.781750658Z
    update_interval: 168h0m0s
    persistent: true
    user: testbot
    group: testbot
