name: Main Branch Update

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  workflow_dispatch:
  push:
    branches: [ 'main' ]
    paths-ignore:
      - 'README.md'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

# To test workflow updates you need to work in a branch directly on viamrobotics/viam-orb-slam3
# and tag your working branch instead of @main in any viamrobotics/viam-orb-slam3 "uses" below.
# Don't forget to tag back to @main before merge.

jobs:
  appimage:
    uses: viamrobotics/viam-orb-slam3/.github/workflows/appimage.yml@main
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

  slack-workflow-status:
      if: ${{ failure() }}
      name: Post Workflow Status To Slack
      needs:
        - appimage
      runs-on: ubuntu-latest
      permissions:
        actions: 'read'
      steps:
        - name: Slack Workflow Notification
          uses: Gamesight/slack-workflow-status@master
          with:
            repo_token: ${{secrets.GITHUB_TOKEN}}
            slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
            channel: '#team-slam-dev'
            name: 'Workflow Status'
